### PR TITLE
feat: add helm chart for bootstrapper

### LINKED ISSUE #22: [request] Helm chart for the tool
Could you add to docs the link to Helm chart to install this app if it exists ?

If not, could you plz publish one to be able to install crd-bootstrap declaratively.

### PR DESCRIPTION
**Pull request by Skarlso**
Closes #22

### CODE REVIEW

**Review by eshepelyuk — COMMENTED** [review]
There is no need to patch Chart.yaml.
Both version and appVersion can be passed via command line args when publishing helm chart to OCI repository.

**Comment by Skarlso** [comment]
Yah this isn't done yet. 😬😁 I just wanted to have something up quickly. I kind of would like to add a values file as well. But don't necessarily see the purpose since I don't have too many settings anyways.

**Comment by Skarlso** [comment]
Okay, I'm trying helm releaser. Let's see if I'm doing the right URLs and stuff...

**Comment by Skarlso** [comment]
Going to finish this on Monday.

**Pull request merged**
